from pydantic import BaseModel, Field
from typing import List, Any

# --- Schemas for Question Generation ---
class InterviewQuestion(BaseModel):
    question: str = Field(description="The interview question generated by the AI.")

class InterviewQuestionsResponse(BaseModel):
    questions: List[InterviewQuestion] = Field(description="A list of generated interview questions.")


# --- Schemas for Answer Evaluation ---
class ScoreBreakdown(BaseModel):
    relevance: int = Field(description="Score (1-10) for relevance to the job description.", ge=1, le=10)
    clarity: int = Field(description="Score (1-10) for clarity and conciseness.", ge=1, le=10)
    impact: int = Field(description="Score (1-10) for using strong examples and demonstrating impact.", ge=1, le=10)

class EvaluationResponse(BaseModel):
    transcribed_text: str = Field(description="The text transcribed from the user's audio.")
    feedback: str = Field(description="Constructive feedback for the user's answer.")
    total_score: float = Field(description="The final weighted score for the answer.", ge=1, le=10)
    score_breakdown: ScoreBreakdown = Field(description="A detailed breakdown of the score.")


# --- NEW: Schemas for Final Summary ---
class InterviewTurn(BaseModel):
    """Represents a single question-and-answer turn in the interview."""
    question: str
    evaluation: EvaluationResponse

class FinalSummaryResponse(BaseModel):
    """The final summary object for the entire interview."""
    overall_feedback: str = Field(description="A comprehensive summary of the candidate's performance, highlighting strengths and areas for improvement across all answers.")
    final_score: float = Field(description="A final, overall score for the entire interview, averaged from all questions.", ge=1, le=10)
    full_history: List[InterviewTurn] = Field(description="A list containing every question and its corresponding evaluation.")


# --- Schemas for WebSocket Communication ---
class WebSocketMessage(BaseModel):
    type: str  # e.g., "status", "question", "evaluation", "end", "final_summary"
    data: Any

class WebSocketError(BaseModel):
    error: str